FROM python:3.10-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    git 
#    && rm -rf /var/lib/apt/lists/*

# Download and extract the desired model(s)
#RUN mkdir -p /root/.local/share/tts/tts_models/en/vctk/vits 
#RUN wget -O - https://github.com/coqui-ai/TTS/releases/download/v0.11.0/vctk-vits.zip | tar -xvf- -C /root/.local/share/tts/tts_models/en/vctk/vits

RUN pip install TTS

WORKDIR /app

ENTRYPOINT ["tts-server"]
CMD ["--model_name", "tts_models/en/vctk/vits"]


