FROM python:3.9-slim

# Install Redis
RUN apt-get update && apt-get install -y redis-server

# Copy your application files
COPY . /app
WORKDIR /app

# Install any needed packages specified in requirements.txt
#RUN pip install --no-cache-dir -r requirements.txt

# Expose the port Redis will run on
EXPOSE 7860

# Start Redis with the custom port and your application
#CMD redis-server --port 7860 --daemonize yes && python app.py
CMD redis-server --port 7860 --daemonize yes